[package]
name = "rc5"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", default-features = false }
num-rational = { version = "0.4", default-features = false, features = ["num-bigint"] }
num-traits = { version = "0.2", default-features = false }
